Repository My-Solar-Garden/rails_backend, pull requests merged in 2020-11, with the labels that each got.

#63 Create new garden
  app/controllers/api/v1/gardens_controller.rb
  spec/requests/api/v1/garden_request_spec.rb
Labels: bug

#61 Add indexes to uid
  db/migrate/20201030204952_add_uid_to_user.rb
  db/schema.rb
Labels: back_end, database

#68 Update user_params in user controller
  app/controllers/api/v1/users_controller.rb
Labels: MVP, back_end, front_end

#80 Update models relationships, dependent destroy.
  app/models/garden.rb
  spec/requests/api/v1/garden_request_spec.rb
Labels: back_end, bug, database

#82 Revert "Revert "Edits plant creation so that plants get same id in our database that …""
  app/controllers/api/v1/gardens/plants_controller.rb
  app/models/garden.rb
  spec/models/garden_spec.rb
  spec/requests/api/v1/gardens/plant_request_spec.rb
Labels: API, MVP, Plant API

#84 Migrate sinatra poros
  app/controllers/api/v1/weather_controller.rb
  app/facades/weather_facade.rb
  app/poros/daily_forecast.rb
  app/poros/weather.rb
  app/serializers/weather_serializer.rb
  app/services/weather_service.rb
  config/routes.rb
  spec/facades/weather_facade_spec.rb
  spec/poros/weather/daily_spec.rb
  spec/poros/weather/weather_spec.rb
  spec/requests/api/v1/weather_serializer_spec.rb
  spec/services/weather_service_spec.rb
Labels: API, Weather-API, back_end

#89 Add test for 100% coverage
  spec/requests/api/v1/users_request_spec.rb
Labels: back_end
